---
- hosts: all
  tasks:
          - name: Gather the rpm package facts
            package_facts:
          - name: Print the rpm package facts
            debug:
                    var: ansible_facts.packages

