---
- hosts: all
  become: true
  tasks:
          - name: Configuring sshd X11 forwarding 
            lineinfile:
                    path: /etc/ssh/sshd_config
                    regexp: '^X11Forwarding yes'
                    line: 'X11Forwarding no'
            notify: Restart sshd

          - name: Configuring MaxAuth Tires to 3
            lineinfile:
                    path: /etc/ssh/sshd_config
                    regexp: '^#MaxAuthTries '
                    line: 'MaxAuthTries 3'
            notify: Restart sshd

  handlers:
          - name: Restart sshd
            service:
                  name: sshd
                  state: restarted 


