---
- name: Example with single pool
  hosts: all
  become: yes
  vars:
    timesync_ntp_servers:
      - hostname: 0.uk.pool.ntp.org
        pool: true
        iburst: true
  roles:
    - rhel-system-roles.timesync

