---
- hosts: database
  become: true
  tasks:
          - name: Creating yum repo for database servers
            yum_repository:
                    name: mysql_repo
                    description: "MySQL 5.7 Community Server"
                    baseurl: http://repo.mysql.com/yum/mysql-5.7-community/el/6/$basearch/
                    gpgkey: https://repo.mysql.com/RPM-GPG-KEY-mysql
                    gpgcheck: 1
                    enabled: yes

