---
- hosts: all
  become: true
  vars:
          ram_mb: 1024
  tasks:
          - name: configure vm.swappiness 
            sysctl:
                    name: vm.swappiness
                    value: "10"
                    state: present
            when: ansible_memtotal_mb >  ram_mb

          - name: if memmory is less than {{ ram_mb }} display msg
            debug:
                    msg: Server has less than {{ ram_mb }}MB ram vmswappiness not configured
            when: ansible_memtotal_mb <= ram_mb 




